api_platform:
    mapping:
        #paths: ['%kernel.project_dir%/src/Entity']
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    #formats: ~

        mime_types: [ 'multipart/form-data' ]
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 15
