App\Entity\GroupeCompetence:
  attributes:
    id:
      groups: [ 'grpecompetence_read','competence:read','referentiel_read' ]
    libelle:
      groups: [ 'grpecompetence_read','competence:read','referentiel_read' ]
    descriptif:
      groups: [ 'grpecompetence_read','competence:read','referentiel_read' ]
    competences:
      groups: [ 'grpecompetence_read' ]
